# Generated by Django 2.0.1 on 2018-01-31 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin', '0004_auto_20180125_0440'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=40)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.Coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
            options={
                'db_table': 'hodlings',
            },
        ),
    ]
