# Generated by Django 2.0.1 on 2018-02-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodlings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hodling',
            old_name='user',
            new_name='userprofile',
        ),
    ]
