# Generated by Django 2.0.1 on 2018-03-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwreset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
