# Generated by Django 2.0.1 on 2018-01-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coin',
            table='coins',
        ),
    ]
