# Generated by Django 2.0.1 on 2018-01-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180110_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='pair',
            field=models.CharField(default='UNK', max_length=10),
            preserve_default=False,
        ),
    ]
