# Generated by Django 2.0.1 on 2018-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20180125_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
